### ISSUE TITLE
how to get the promise result

### ISSUE THREAD

**Issue by lgl2017** [HiRoFa/quickjs_es_runtime#83]

**Comment by lgl2017** [comment]
I have a async code, but I can not get the promise result. And I have not found some explame for it.Could you help me?

**Comment by lgl2017** [comment]
> _No description provided._

**Comment by andrieshiemstra** [comment]
Hi lgl2017, 

Sure, here goes.. most simple example I could think of
```rust
#[tokio::test]
    async fn test_promise_async() {
        let rt = init_test_rt();
        let jsvf = rt
            .eval(
                None,
                Script::new("test_prom_async.js", "Promise.resolve(123)"),
            )
            .await
            .expect("script failed");
        if let JsValueFacade::JsPromise { cached_promise } = jsvf {
            let res = cached_promise
                .get_promise_result()
                .await
                .expect("promise resolve send code stuf exploded");
            match res {
                Ok(prom_res) => {
                    if prom_res.is_i32() {
                        assert_eq!(prom_res.get_i32(), 123);
                    } else {
                        panic!("promise did not resolve to an i32.. well that was unexpected!");
                    }
                }
                Err(e) => {
                    panic!("prom was rejected: {}", e.stringify())
                }
            }
        }
    }
```

So, when the script passed to rt.eval return a Promise the QuickJsRuntimeFacade (rt) return a JsValueFacade::JsPromise which in turn has a ```CachedJsPromiseRef``` which has a method ```get_promise_result```

What that method actualy does is open a channel and return the receiver, the sender is invoked by closures added to the promise reactions (then and catch) so a Result or Error is sent when the promise resolves. 

since ```get_promise_result``` is an async function you can .await the result in async code
